# Generated by Django 2.0.10 on 2020-04-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GermanyStateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=None, default='code', max_length=255, null=True, unique=True)),
                ('german', models.CharField(blank=None, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GermanyStateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.IntegerField(blank=None, default=0, null=True)),
                ('death', models.IntegerField(blank=None, default=0, null=True)),
                ('recovered', models.IntegerField(blank=None, default=0, null=True)),
                ('death_rate', models.DecimalField(blank=None, decimal_places=2, default=0, max_digits=9, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseapp.DateFlag')),
                ('germany_state_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseapp.GermanyStateCode')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='germanystateitem',
            unique_together={('date_flag', 'germany_state_code')},
        ),
    ]
